---
# ansible-playbook configureApache.yaml

- name: Installing of Apache and configuring new users and packges on Kali
  hosts: kali

  tasks:
  - name: create Apache host index.html
    copy:
      content: "Ervie John T. Villareal"
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: "0644"
    register: apache_index

  - name: Start apache2 service
    service:
      name: apache2
      state: restarted
      enabled: yes
    when: apache_index.changed

  - name: whitelist apache2 in ufw
    ufw:
      rule: allow
      port: '80'
      protocol: tcp 
  
  - name: disable ufw
    ufw:
      state: disabled

- name: Check web service if up
  hosts: localhost
  connection: local
  become: no

  tasks:
  - name: Check web service if up
    uri: 
      url: http://192.168.200.2/